define(["DQX/Utils", "DQX/Controls", "DQX/Msg", "DQX/Popup"],
    function (DQX, Controls, Msg, Popup) {
        var MetaData = {};


        MetaData.serverUrl="http://panoptes.cggh.org/sandbox/dqx_server30/app";

        //////////////////////////////////////////////////////////////////////////////////////////////////////////////
        //Data source tables
        //////////////////////////////////////////////////////////////////////////////////////////////////////////////

        //theMetaData1.database = 'pf21c';
        MetaData.database = 'pfpopgen';
        MetaData.tableSNPInfo = 'pfsnprel21'; //SNP information (including population frequencies)
        MetaData.tableAnnotation = 'pfannotrel21'; //Genome annotation

        //////////////////////////////////////////////////////////////////////////////////////////////////////////////
        //Define the metadata that is generated by the client (NOTE: some of this stuff should move to the server)
        //////////////////////////////////////////////////////////////////////////////////////////////////////////////


        //////// Information about the chromosomes
        MetaData.chromosomes = [
            { id: 'MAL1', len: 0.7 },
            { id: 'MAL2', len: 1 },
            { id: 'MAL3', len: 1.2 },
            { id: 'MAL4', len: 2 },
            { id: 'MAL5', len: 2 },
            { id: 'MAL6', len: 2 },
            { id: 'MAL7', len: 2 },
            { id: 'MAL8', len: 2 },
            { id: 'MAL9', len: 2 },
            { id: 'MAL10', len: 2 },
            { id: 'MAL11', len: 4 },
            { id: 'MAL12', len: 4 },
            { id: 'MAL13', len: 4 },
            { id: 'MAL14', len: 4 }
        ];
        $.each(MetaData.chromosomes, function (idx, chr) { chr.name = chr.id; });


        return MetaData;
    });
