define(["DQX/Utils", "DQX/Controls", "DQX/Msg", "DQX/Popup"],
    function (DQX, Controls, Msg, Popup) {
        var MetaData = {};


        //MetaData.serverUrl="http://localhost:8000/app01";
        //MetaData.serverUrl="http://localhost/DQXServer/app";
        MetaData.serverUrl="http://panoptes.cggh.org/sandbox/dqx_server_test/app";

        //////////////////////////////////////////////////////////////////////////////////////////////////////////////
        //Data source tables
        //////////////////////////////////////////////////////////////////////////////////////////////////////////////

        //theMetaData1.database = 'pf21c';
        MetaData.database = 'pfpopgen';
        MetaData.tableSNPInfo = 'pfsnprel21'; //SNP information (including population frequencies)
        MetaData.tableAnnotation = 'pfannotrel21'; //Genome annotation

        //////////////////////////////////////////////////////////////////////////////////////////////////////////////
        //Define the metadata that is generated by the client (NOTE: some of this stuff should move to the server)
        //////////////////////////////////////////////////////////////////////////////////////////////////////////////


        //////// Information about the chromosomes
        MetaData.chromosomes = [
            { id: 'MAL1', len: 0.7 },
            { id: 'MAL2', len: 1 },
            { id: 'MAL3', len: 1.2 },
            { id: 'MAL4', len: 2 },
            { id: 'MAL5', len: 2 },
            { id: 'MAL6', len: 2 },
            { id: 'MAL7', len: 2 },
            { id: 'MAL8', len: 2 },
            { id: 'MAL9', len: 2 },
            { id: 'MAL10', len: 2 },
            { id: 'MAL11', len: 4 },
            { id: 'MAL12', len: 4 },
            { id: 'MAL13', len: 4 },
            { id: 'MAL14', len: 4 }
        ];
        $.each(MetaData.chromosomes, function (idx, chr) { chr.name = chr.id; });

        MetaData.showClusterData = false;

        MetaData.populations=[
            { freqid:'NRAF_WAF', name:"West Africa", color:DQX.Color(1,0,0) },
            { freqid:'NRAF_EAF', name:"East Africa", color:DQX.Color(0,0,1) }
            //{ freqid:'NRAF_SEA', name:"South-east Asia", color:DQX.Color(0,0.7,0.5) }
        ];

        MetaData.summaryFolder='Tracks-PfPopGen2.1';//Location of the summary data, relative to the base path defined by DQXServer
        MetaData.summaryConfig='Summ01';//ID of the summary configuration used


        //List of all the summary profiles displayed in the app
        MetaData.summaryProfiles=[
            { id:'GC300', name:"%GC" },
            { id:'Uniqueness', name:"Uniqueness" }
        ];



        return MetaData;
    });
